Plugin 'tpope/vim-sensible'
Plugin 'tpope/vim-fugitive'
Plugin 'ervandew/supertab'
Plugin 'scrooloose/nerdtree'
Plugin 'vim-scripts/gitignore'
Plugin 'vim-scripts/showtrailingwhitespace'
Plugin 'vim-scripts/deletetrailingwhitespace'

Plugin 'altercation/vim-colors-solarized'
Plugin 'tomasr/molokai'
